@startuml sequences-consumer

skinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam maxmessagesize 200


skinparam ParticipantPadding 30
skinparam BoxPadding 30
skinparam SequenceBoxBackgroundColor AliceBlue
skinparam ActorBorderColor SaddleBrown
skinparam sequenceMessageAlign left

participant "Tansport Layer" as Transport << (S, LightBlue) >> order 0
box "Consumer"
participant "Consumer Adapter" as Adapter << (C,#ADD1B2) >> order 1
participant "Consumer" as Consumer << (C,#ADD1B2) >> order 2
end box
box JobExecution
participant JobHandler << (C,#ADD1B2) >> order 3
end box
participant "Upper Layer" as Upper << (S, LightBlue) >> order 4

group Initialization
    Upper -> Consumer : subscribe("command")
    Consumer -> Adapter : subscribe(handler)
end

group Invalid command message
    Transport -> Adapter : execute(command)
    activate Adapter
    Adapter -> Consumer : handler(command, done)
    activate Consumer
    Consumer -> Consumer : isValidCommand(command)
    Consumer -> Adapter : done(error)
    deactivate Consumer
    Adapter -> Transport : done(error)
    deactivate Adapter
end

group Command message for other instance
    Transport -> Adapter : execute(command)
    activate Adapter
    Adapter -> Consumer : handler(command, done)
    activate Consumer
    Consumer -> Consumer : isValidCommand(command)
    Consumer -> Consumer : isCommandToInstance(command)
    Consumer -> Adapter : done(response)\n404 Not Found
    deactivate Consumer
    Adapter -> Transport : done(response)\n404 Not Found
    deactivate Adapter
end

group Command message for other instance
    Transport -> Adapter : execute(command)
    activate Adapter
    Adapter -> Consumer : handler(command, done)
    activate Consumer
    Consumer -> Consumer : isValidCommand(command)
    Consumer -> Consumer : isCommandToInstance(command)
    Consumer -> Consumer : hasDefaultRespond(command)
    Consumer -> Adapter : done(response)\n 102 Processing\n 200 OK\n 400 Bad Request\n 500 Internal Server Error\n 501 Not Implemented
    deactivate Consumer
    Adapter -> Transport : done(response)\n 102 Processing\n 200 OK\n 400 Bad Request\n 500 Internal Server Error\n 501 Not Implemented
    deactivate Adapter
end

group Valid and supported command message
    Transport -> Adapter : execute(command)
    activate Adapter
    Adapter -> Consumer : handler(command, done)
    activate Consumer
    Consumer -> Consumer : isValidCommand(command)
    Consumer -> Consumer : isCommandToInstance(command)
    Consumer -> Consumer : hasDefaultRespond(command)
    Consumer -> Consumer : executeCommand(command)
    box JobExecution
    create JobHandler
    end box
    Consumer --> JobHandler : subscribe("done")
    activate JobHandler
    Consumer --> Upper : emit("command", JobHandler)
    activate Upper
    Upper -> JobHandler : done()
    deactivate Upper
    JobHandler --> Consumer : emit("done")
    deactivate JobHandler
    destroy JobHandler
    Consumer -> Adapter : done(response)
    deactivate Consumer
    Adapter -> Transport : done(response)
    deactivate Adapter
end

@enduml