export const DEFAULT_AGENTXPDU_NETWORK_BYTE_ORDER = 0x10;
export const DEFAULT_AGENTXPDU_SESSION_ID = 0;
export const DEFAULT_AGENTXPDU_TRANSACTION_ID = 0;

export const DEFAULT_AGENTXPDU_TIMEOUT = 0;
export const DEFAULT_AGENTXPDU_PRIORITY = 127;
export const DEFAULT_AGENTXPDU_RANGE_SUBID = 0;
export const DEFAULT_AGENTXPDU_SYS_UP_TIME = 0;
export const DEFAULT_AGENTXPDU_INDEX = 0;
export const DEFAULT_AGENTXPDU_ERROR = 0;

export const DEFAULT_AGENTXPDU_OID_ADDRESS_PREFIX = 0;
