## Template for a monorepository based on GitFlow, Docker and DockerCompose in Netin Development Ecosystem
name: mdf-js$(Date:yyyyMMdd)$(Rev:.r)
## CI trigger based on GitFlow
trigger:
  - master
  - develop
  - release/*
  - hotfix/*
  - feature/*
pr:
  - master
  - develop
## Netin - Variables
variables:
    ## Artifact name
  - name: artifactName
    value: 'mdf-js-api'
    ## Node version
  - name: nodeVersion
    value: '18'
    ## Releases Wiki page
  - name: artifactWikiFileName
    value: '@mdf.js%2Djs-%2D-API'
  ## GitFlow variables for branch maching
  - template: mdf-pipelines-variables.yml
stages:
  - stage: 'APP'
    displayName: 'Application Build'
    pool:
      name: NUCHUB
    jobs:
      - job: 'CODE_QUALITY'
        displayName: 'Code Quality Assurance'
        workspace:
          clean: all
        timeoutInMinutes: 30
        steps:
          - checkout: self
            clean: true
            persistCredentials: true
            fetchDepth: 0
          - template: mdf-setup-gitversion.yml
          - template: mdf-setup-node-and-yarn.yml
            parameters: 
              nodeVersion: ${{variables.nodeVersion}}
          - template: mdf-test-monorepo.yml
          - template: mdf-test-sonarqube-analysis.yml
          - template: mdf-publish-artifacts-lerna.yml
  # - template: mdf-release-library-version.yml
  #   parameters:
  #     artifactName: ${{variables.artifactName}}
  #     artifactWikiFileName: ${{variables.artifactWikiFileName}} 
