export const RECEIVER_DEFAULT_ENGINE_BOOTS = 0;
export const RECEIVER_DEFAULT_ENGINE_TIME = 10;
export const RECEIVER_DEFAULT_TRANSPORT = 'udp4';
export const RECEIVER_DEFAULT_PORT = 162;
export const RECEIVER_DEFAULT_DISABLE_AUTHORIZATION = false;
export const RECEIVER_DEFAULT_INCLUDE_AUTHENTICATION = false;
export const RECEIVER_DEFAULT_CONTEXT = '';
