@startuml Provider-States-Methods

!define DARKGREEN
!include ./styles/style.puml

skinparam backgroundColor transparent

!STOPPED_STATE = "1a66c2"
!RUNNING_STATE = "228811"
!FAILED_STATE = "CC0033"

skinparam State {
  borderColor #1b1b1b
  FontColor #fff
  FontName Serif
  FontSize 11
  stereotypeFontColor #aaa
  stereotypeFontSize 11
  arrowColor #fff
  arrowFontName Serif
  arrowFontColor #bbb
  arrowFontSize 11
  startColor $ACCENT
  endColor $ACCENTDARK
}


state STOPPED {
    state STOPPED #STOPPED_STATE: Administratively offline or not\n initialized so resources cannot\n be accessed
}
state RUNNING {
    state RUNNING #RUNNING_STATE: Online and initialized, the access\n to resources is possible
}
state ERROR {
    state ERROR #FAILED_STATE: Online, but in a degraded state,\n the access to resources is not\n possible
}

[*] -[#black]-> STOPPED : "instance created"
STOPPED -[#STOPPED_STATE]-> STOPPED : stop()
STOPPED -[#RUNNING_STATE]-> RUNNING : start()
STOPPED -[#FAILED_STATE]-> ERROR : fail()
RUNNING -[#RUNNING_STATE]-> RUNNING : start()
RUNNING -[#STOPPED_STATE]-> STOPPED : stop()
RUNNING -[#FAILED_STATE]-> ERROR : fail()
ERROR -[#FAILED_STATE]-> ERROR: fail()
ERROR -[#RUNNING_STATE]-> RUNNING: start()
ERROR -[#STOPPED_STATE]-> STOPPED: stop()

@enduml